### PR TITLE
Dependency updates

### PR DESCRIPTION
**Pull request by 123Haynes**
This PR updates the dependencies to their latest versions, fixes maven warnings, migrates the tests from Junit 4 to Junit 5 and  replaces the deprecated AESFastEngine with AESEngine 😃

### CODE REVIEW

**Comment by Neustradamus** [comment]
@123Haynes: Thanks a lot for your PRs (https://github.com/jitsi/jitsi-srtp/pull/13 and this), I am very happy :)

A long time ago, I have communicated about old dependencies on GitHub, on Twitter (private and public), and recently on the forum.

Can you look in https://github.com/jitsi/jitsi desktop client repository too?

I have done PR a long time ago (and recently) without solutions:
- https://github.com/pulls?q=is%3Apr+author%3ANeustradamus+org%3Ajitsi+

In this organization:
- Bouncycastle: https://github.com/search?q=org%3Ajitsi+bouncycastle&type=Code
- SLF4J: https://github.com/search?q=org%3Ajitsi+bouncycastle&type=Code
- ...

**Comment by Neustradamus** [comment]
@123Haynes: I have updated the first ticket with all PRs included yours, can you look if it is good or not for other?
- https://github.com/jitsi/jitsi/issues/562

**Comment by Neustradamus** [comment]
@ibauersachs: Can you look here?

**Comment by ibauersachs** [comment]
No, as this repository will become obsolete when all other projects are updated to BC 1.65. I will archive it once this is done.

**Comment by Neustradamus** [comment]
@ibauersachs: Ok!
Have you looked other projects?
I have done several PRs, but you can update more code than me without problem :)

**Comment by 123Haynes** [comment]
Cool 👍 

If this repository is becoming obsolete this PR isn't needed anymore. Closing it 😃

**Comment by Neustradamus** [comment]
@123Haynes: I think it is not the solution...

A lot of other tickets/PRs about Bouncy Castle, all projects are not solved yet...
- https://github.com/jitsi/jitsi/issues/562
- https://github.com/jitsi/jitsi/pull/564
- https://github.com/jitsi/bccontrib/pull/3
- https://github.com/jitsi/jitsi-srtp/pull/13
- https://github.com/jitsi/libjitsi/pull/522
- https://github.com/jitsi/jitsi-media-transform/pull/253
- https://github.com/jitsi/jigasi/pull/259
- https://github.com/jitsi/otr4j/pull/32
- https://github.com/jitsi/jitsi-hammer/issues/36
- https://github.com/jitsi/zrtp4j/pull/3

- https://github.com/search?p=1&q=org%3Ajitsi+Bouncy+Castle&type=Issues

**Pull request closed without merging**
